package com.example.appium_sample.utils;

import com.example.appium_sample.R;
import com.example.appium_sample.model.FruitModel;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class DataProvider {
    public static List<FruitModel> getData() {
        List<FruitModel> list = new ArrayList<>();
        list.add(new FruitModel("Apple", 5.20f, R.drawable.apple, "Apples are a sweet fleshy fruit that grow around the world. Believed to originate in Central Asia, there are now hundreds of varieties of apples, ranging from sweet to sour. Nutritionally speaking, apples are a relatively high-carbohydrate fruit and their most significant nutrient is vitamin C. They’re a very versatile fruit; while often eaten as a snack, they’re also used in a variety of dessert recipes."));
        list.add(new FruitModel("Avocado", 7.5f, R.drawable.avocado, "Avocados are an interesting fruit because they are very low in carbohydrate yet high in healthy fats. The fruit originated in South America, possibly in Mexico or Peru, and it was first referred to in English by the name of “crocodile pear”. One of the best things about the avocado is just how adaptable it is. For instance, you may have heard of ‘avocado toast’, a trendy breakfast at the moment. However, there are many different ways to use avocados – such as making guacamole, avocado ice-cream, chocolate mousses, and many other interesting dishes. Cold-pressed avocado oil also gives olive oil a run for its money in the ‘healthiest oil’ department; it’s a heat-stable fat that contains various protective nutrients. Avocados are extremely nutrient-dense, and they are rich in fiber, protein, vitamins, and minerals – especially potassium."));
        list.add(new FruitModel("Banana", 3.2f, R.drawable.bananas, "The banana is a tropical fruit with a long body covered in a yellow skin. It’s a very common fruit and—despite needing a hot climate—it’s available in most countries. Since bananas have a very sweet taste, dessert recipes often use them. In particular, banana splits, banana milk, and banana bread are some of the most popular options. Due to their accessibility and inexpensive price, bananas are one of the most popular types of fruit in the world."));
        list.add(new FruitModel("Blackberries", 8.56f, R.drawable.blackberries, "Blackberries are one of the tastiest fruits around. They are a small edible fruit with a big taste, and botanically they are a kind of berry that grow on brambles. The fruit has a sweet and succulent taste despite being relatively low in fructose compared to most types of fruit. Blackberries are one of the most commonly cultivated fruits. However, we can also find them growing in their wild state – which purportedly have a better nutritional profile and more polyphenols (5). Combine them with some fresh cream for a delicious, sweet and creamy dessert. Blackberries are especially good for vitamin C and the health benefits it provides."));
        list.add(new FruitModel("Cherry", 6.6f, R.drawable.cherry, "Cherries are one of the most popular fruit varieties, and they are technically a drupe – a fruit with a hard stone inside. The cherry is a small fruit with a sweet and juicy taste. There are also two main types of cherry; sour cherries and sweet cherries. These two varieties are fairly similar, but sour cherries have the slightly better nutritional profile. Sour cherries predominantly grow in Russia, Eastern Europe and Southern Asia. On the other hand, Turkey and the United States are the biggest producers of sweet cherries. Cherries are a seasonal fruit, but frozen cherries are available around the year."));
        list.add(new FruitModel("Grape", 2.5f, R.drawable.grape, "Grapes are one of the most prevalent types of fruit, and we can find them almost everywhere. Grapes are very versatile too, and they form the basis of many different wines, juices, jams, and dessert products. Not many people know this, but grapes are botanically a kind of berry. Although there are thousands of different grape varieties, they are typically classified as either white (green), red, purple, or black. The health benefits of grapes are purported to come from their high polyphenol content. However, grapes are also one of the highest-sugar fruits. As a result, red wine is often thought of as a health drink since it contains concentrated polyphemus and little sugar."));
        list.add(new FruitModel("Guava", 5.9f, R.drawable.guava, "Guava is a tropical fruit that grows in tropical and subtropical areas. Generally speaking, we can find it in Mexico and elsewhere in Central and Southern America. Guava has an interesting appearance and it has a lime-green skin with a pink fleshy center. Depending on the ripeness of the fruit, guavas may taste anything from slightly sour to sweet. Hint: as a guava ripens, its green skin will slowly turn to a light yellow color. If you want a sweeter tasting guava, go for one which has tinges of yellow on its skin. Nutritionally, guavas are an exceptional provider of vitamin C – just one small fruit supplies 209% of the RDA."));
        list.add(new FruitModel("Kiwi", 2.2f, R.drawable.kiwi, "Kiwifruit is a soft, green and juicy edible fruit. It has the alternate name of ‘Chinese gooseberry’ and it is one of the most famous types of fruit in the world. The fruit is relatively easy to grow and it’s easy to find in most developed countries. Kiwifruit taste slightly sour, but mostly sweet, and their green flesh and black seeds are encased in an olive-colored furry skin. Kiwis contain an impressive amount of vitamin C. Notably, one small fruit contains more than the daily RDA."));
        list.add(new FruitModel("Lemon", 1.55f, R.drawable.lemon, "If you like sour fruits, then here’s another – the lemon is a yellow citrus fruit native to Asia. Lemons house a tart soft flesh behind a thick yellow skin, and they are a famous culinary fruit. For one thing, thousands of recipes call for a squeeze of fresh lemon juice. Lemons also hold value for cleaning uses; the reason for this is their high concentration of citric acid. In addition, there is a wide variety of lemon-based food products, such as lemon cakes, lemon juice, lemon jam, and lemon tea."));
        list.add(new FruitModel("Mango", 2.3f, R.drawable.mango, "Sometimes referred to as the “king of fruits”, mangoes are a tropical fruit with an extremely sweet and juicy flesh. They are native to South Asia, and they’re a common fruit in countries such as India, the Philippines, and Thailand. Mangoes contain a stone (making them a drupe) surrounded by sweet yellow flesh; this taste is slightly sweet, soft, and tangy. Generally, people eat the fruit in its raw, whole state, but there are also many smoothie and dessert recipes. The sweet taste makes sense when we consider that mangoes are one of the highest carbohydrate/sugar fruits."));
        list.add(new FruitModel("Mulberry", 8.45f, R.drawable.mulberry, "Mulberries come in all shapes and sizes, and they are a popular berry that grow around the world. There are many different kinds of mulberry, but there are three main varieties; black, red, and white. Black and red mulberries are native to the United States, while the white varieties mainly grow in China. Mulberries are popular in fresh and dried form; black and red mulberries are sweet and juicy with a slightly tart flavor. However, since white mulberries are predominantly from China, we usually buy them in their dried state. These berries are much smaller than the red and black varieties, and they have a much sweeter taste too."));
        list.add(new FruitModel("Orange", 2.56f, R.drawable.orange, "Oranges are among the most common fruit in the world. The orange is a citrus fruit and, surprisingly, it is a hybrid rather than an original species. If you didn’t know about this point, then oranges are actually a hybrid of the pomelo and mandarin. Oranges have a tough outer peel that encases the soft, juicy center. Generally speaking, the fruit has a sweet and (very slight) sour taste. However, there are hundreds of orange varieties and they can vary between sweet, bitter, and sour. The sweet varieties are generally the edible kind we find in shops and in orange juice. Oranges are a relatively high-carbohydrate fruit and they provide a decent amount of vitamin C."));
        list.add(new FruitModel("Strawberry", 3.25f, R.drawable.strawberry, "The strawberry is one of the most common (and beloved) fruits in the world. Strawberries are thought to be berries, but this is not botanically true, and they are an accessory fruit. Commonly eaten fresh, with cream, or in a range of desserts, strawberries are a soft and sweet-tasting fruit. In addition to their taste, strawberries actually smell sweet too – if that is possible. Given this, strawberry flavors and scents are prevalent in candy, soaps, creams, lip balms and many other products."));
        Collections.shuffle(list);
        return list;
    }
}
